version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: odoo-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./odoo-nginx:/etc/nginx/conf.d
    networks:
      - odoo-network
    restart: always
    tty: true
    
  postgres:
    container_name: odoo-db
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo18@2024
      POSTGRES_DB: postgres
    restart: always 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-network
    ports:
      - "5433:5432"

  odoo18:
    container_name: odoo18-web
    image: odoo:18.0
    user: root
    depends_on:
      - postgres
    ports:
      - "10036:8069"
      - "20036:8072" # live chat
    tty: true
    command: odoo --config=/etc/odoo/odoo.conf
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    volumes:
      - ./odoo-addons-customs:/mnt/extra-addons
      - ./odoo-addons-3rd:/mnt/3rd-addons
      - ./odoo-ee:/mnt/odoo-ee
      - ./odoo-config:/etc/odoo/
      - ./odoo-data:/var/lib/odoo/
      - ./odoo-logs:/var/log/odoo/
    restart: always     
    networks:
      - odoo-network        # run as a service

volumes:
  odoo-nginx:
  odoo-addons-customs:
  odoo-addons-3rd:
  odoo-ee:
  odoo-config:
  odoo-data:
  odoo-logs:
  postgres-data:

networks:
  odoo-network:
    driver: bridge